package cl.dssm.soporteimagenes.enums;

public enum DifficultyType {
    CONTRASENA_NO_FUNCIONA,
    DATOS_CONTACTO_NO_ACTUALIZADOS,
    SIN_CORREO_REGISTRADO,
    NO_RECIBI_COMPARTIR_ESTUDIOS,
    NO_RECIBI_RECUPERAR_CONTRASENA,
    TUTOR_RESPONSABLE_SIN_ACCESO,
    OTRO
}
